import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
const ZillaSlab = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: "300",
});
export const metadata: Metadata = {
  title: "E-commerce Web App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ZillaSlab.className} bg-[#f4f4f4]`}>{children}</body>
    </html>
  );
}
